import type { PageContent } from '../types';

export const pageContent: PageContent = {
  urgencyBar: {
    enabled: true,
    text: 'Válido só hoje dia {data}',
  },
  hero: {
    image: '/images/hero-mockup-atividades-minecraft.webp',
    imageAlt: '+147 Atividades Escolares com Minecraft - Mockup Completo do Kit',
    headline: '+147 ATIVIDADES ESCOLARES COM MINECRAFT PRONTAS PARA IMPRIMIR E FAZER SEU FILHO LARGAR O CELULAR E APRENDER BRINCANDO',
    body: 'Tenha sempre em mãos dinâmicas do 1º ao 5º ano, organizadas por série, para acabar com a dor de cabeça de pedir toda hora para seu filho sair das telas e fazer algo educativo.',
    ctaLabel: 'QUERO AGORA',
    securityImage: '/images/selos-seguranca-compra.svg',
    securityImageAlt: 'Selos de compra segura, satisfação garantida e privacidade protegida',
  },
  results: {
    title: 'Veja o que pais e mães estão falando depois de apresentar aos filhos uma maneira muito mais divertida de praticar o que aprendem na escola.',
    items: [
      {
        src: '/images/resultado-01.webp',
        alt: 'Depoimento de mãe sobre as atividades de Minecraft 01',
        label: 'Depoimento 01',
        ratio: '2:3',
      },
      {
        src: '/images/resultado-02.webp',
        alt: 'Depoimento de pais elogiando o aprendizado com Minecraft 02',
        label: 'Depoimento 02',
        ratio: '2:3',
      },
      {
        src: '/images/resultado-03.webp',
        alt: 'Feedback positivo da evolução da criança com o kit 03',
        label: 'Depoimento 03',
        ratio: '2:3',
      },
      {
        src: '/images/resultado-04.webp',
        alt: 'Relato de família com o caderno de atividades Minecraft 04',
        label: 'Depoimento 04',
        ratio: '2:3',
      },
    ],
  },
  modulesSection: {
    title: 'UM MUNDO DE DESAFIOS PARA SEU FILHO EXPLORAR FORA DAS TELAS',
    subtitle: 'São +147 atividades organizadas por série para você escolher, imprimir e entregar sempre que quiser transformar o tempo livre em um momento divertido e educativo.',
  },
  modulesCarousel: [
    {
      src: '/images/atividade-01.png.webp',
      alt: 'Atividade 01 do Caderno de Atividades Minecraft',
      label: 'Atividade 01',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-02.png.webp',
      alt: 'Atividade 02 do Caderno de Atividades Minecraft',
      label: 'Atividade 02',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-03.png.webp',
      alt: 'Atividade 03 do Caderno de Atividades Minecraft',
      label: 'Atividade 03',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-04.png.webp',
      alt: 'Atividade 04 do Caderno de Atividades Minecraft',
      label: 'Atividade 04',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-05.png.webp',
      alt: 'Atividade 05 do Caderno de Atividades Minecraft',
      label: 'Atividade 05',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-06.png.webp',
      alt: 'Atividade 06 do Caderno de Atividades Minecraft',
      label: 'Atividade 06',
      ratio: '3:4' as const,
    },
    {
      src: '/images/atividade-07.png.webp',
      alt: 'Atividade 07 do Caderno de Atividades Minecraft',
      label: 'Atividade 07',
      ratio: '3:4' as const,
    },
  ],
  modules: [
    {
      src: '',
      alt: 'Módulo 01: Missões do Mundo dos Blocos',
      label: 'Módulo 01',
      ratio: '1:1' as const,
      eyebrow: 'MÓDULO 01',
      title: 'MISSÕES DO MUNDO DOS BLOCOS',
      description: 'Para transformar conteúdos escolares em pequenas missões que despertam a curiosidade. Seu filho começa explorando desafios temáticos inspirados no universo do Minecraft, desenvolvidos para deixar a prática escolar mais visual, divertida e interessante. Dentro deste módulo: desafios introdutórios, exercícios visuais e missões adequadas aos conteúdos correspondentes às séries contempladas pelo material.',
    },
    {
      src: '',
      alt: 'Módulo 02: Desafios dos Aventureiros',
      label: 'Módulo 02',
      ratio: '1:1' as const,
      eyebrow: 'MÓDULO 02',
      title: 'DESAFIOS DOS AVENTUREIROS',
      description: 'Para praticar enquanto avança por novos desafios. Aqui, a criança encontra novas missões para reforçar conteúdos do 1º ao 5º ano sem aquela sensação de estar diante de mais uma tarefa escolar cansativa. A temática transforma cada página em um novo desafio e ajuda você a apresentar o momento de estudo de uma forma muito mais atrativa.',
    },
    {
      src: '',
      alt: 'Módulo 03: Jornada dos Mestres',
      label: 'Módulo 03',
      ratio: '1:1' as const,
      eyebrow: 'MÓDULO 03',
      title: 'JORNADA DOS MESTRES',
      description: 'Para continuar evoluindo e conquistar desafios cada vez mais estimulantes. Uma seleção de dinâmicas para continuar praticando conteúdos escolares enquanto a criança avança por novas missões, completa desafios e percebe sua própria evolução. Tudo organizado para você encontrar rapidamente o conteúdo adequado e ter uma opção educativa pronta sempre que precisar.',
    },
  ],
  bonusesSection: {
    title: 'E PARA DEIXAR ESSA AVENTURA AINDA MAIS COMPLETA...',
    subtitle: 'Na Oferta Completa, seu filho também recebe 3 bônus temáticos que ajudam a transformar cada atividade concluída em uma nova conquista.',
  },
  bonuses: [
    {
      src: '/images/bonus-01-mapa-de-progresso.webp',
      alt: 'Bônus 01: Mapa de Progresso Matemático',
      label: 'Bônus 01',
      ratio: '1:1' as const,
      eyebrow: 'BÔNUS 01',
      title: 'MAPA DE PROGRESSO MATEMÁTICO',
      description: 'A criança acompanha o que já concluiu e visualiza as próximas conquistas.',
      value: 'GRÁTIS NO COMBO',
    },
    {
      src: '/images/bonus-02-cartoes-de-recompensa.webp',
      alt: 'Bônus 02: Cartões de Recompensa',
      label: 'Bônus 02',
      ratio: '1:1' as const,
      eyebrow: 'BÔNUS 02',
      title: 'CARTÕES DE RECOMPENSA',
      description: 'Reforce o esforço da criança com pequenas metas e recompensas visuais.',
      value: 'GRÁTIS NO COMBO',
    },
    {
      src: '/images/bonus-03-probleminhas-matematica.webp',
      alt: 'Bônus 03: 100 Probleminhas de Matemática',
      label: 'Bônus 03',
      ratio: '1:1' as const,
      eyebrow: 'BÔNUS 03',
      title: '100 PROBLEMINHAS DE MATEMÁTICA',
      description: 'Mais situações-problema para interpretar, organizar os dados e encontrar a resposta.',
      value: 'GRÁTIS NO COMBO',
    },
  ],
  offersSection: {
    title: 'ESCOLHA COMO SEU FILHO VAI COMEÇAR ESSA AVENTURA',
    paymentSecurityImage: '/images/metodos-pagamento-seguranca.svg',
    paymentSecurityAlt: 'Métodos de pagamento e selos de compra segura, satisfação garantida e privacidade protegida',
  },
  offers: {
    simple: {
      title: 'PACOTE SIMPLES',
      items: [
        '+147 atividades temáticas',
        'Acesso digital imediato',
        'Acesso vitalício',
      ],
      previousPrice: '',
      installmentCount: 1,
      installmentValue: '',
      cashValue: 'R$ 9,90',
      paymentType: 'Pagamento único',
      ctaLabel: 'PACOTE SIMPLES',
    },
    complete: {
      badge: '⭐ MAIS VENDIDO',
      title: 'PACOTE COMPLETO',
      items: [
        { label: '+147 atividades temáticas' },
        { label: 'Conteúdos do 1º ao 5º ano' },
        { label: 'Material organizado por série' },
        { label: 'Arquivos prontos para impressão' },
        { label: 'Acesso digital imediato' },
        { label: 'Acesso vitalício' },
        { label: '🎁 Mapa de Progresso Matemático', value: 'GRÁTIS NO COMBO' },
        { label: '🎁 Cartões de Recompensa', value: 'GRÁTIS NO COMBO' },
        { label: '🎁 100 Probleminhas de Matemática', value: 'GRÁTIS NO COMBO' },
      ],
      previousPrice: 'R$ 34,70',
      previousPriceLabel: 'Valor dos bônus separadamente:',
      installmentCount: 1,
      installmentValue: '',
      cashValue: 'R$ 27,90',
      paymentType: 'Pagamento único',
      ctaLabel: 'PACOTE COMPLETO',
    },
    popup: {
      eyebrow: '⛏️ ESPERA! ANTES DE COMEÇAR SUA PRIMEIRA MISSÃO...',
      message: 'Leve a experiência completa e transforme cada atividade concluída em uma nova conquista. Você escolheu as +147 atividades, mas pode adicionar agora os 3 materiais extras criados para tornar a experiência ainda mais envolvente para seu filho.',
      title: 'CONDIÇÃO ESPECIAL DE UPGRADE',
      previousPrice: '',
      installmentCount: 1,
      installmentValue: '',
      cashValue: 'R$ 17,90',
      paymentType: 'Pagamento único',
      ctaLabel: 'PACOTE COMPLETO',
      secondaryLabel: 'PACOTE SIMPLES',
    },
  },
  guarantee: {
    image: '/images/selo-garantia-7-dias.svg',
    imageAlt: 'Selo de garantia de 7 dias',
    days: 7,
    title: '7 DIAS PARA EXPLORAR SEM RISCO',
    body: 'Você terá 7 dias de garantia para acessar o material e conferir se ele faz sentido para sua família. Se dentro desse período entender que o produto não atende às suas expectativas, basta solicitar o reembolso conforme as condições da plataforma. Você experimenta. O risco fica com a gente.',
  },
  faqSection: {
    title: 'PERGUNTAS FREQUENTES',
  },
  faq: [
    {
      question: '1. Para quais séries as atividades são indicadas?',
      answer: 'O material foi desenvolvido para crianças do 1º ao 5º ano, com as atividades organizadas por série para facilitar a escolha do que usar em cada momento.',
    },
    {
      question: '2. Meu filho precisa saber jogar Minecraft?',
      answer: 'Não. A temática é utilizada para tornar a experiência visual mais familiar e divertida. A criança não precisa jogar ou conhecer as regras do jogo para realizar as atividades.',
    },
    {
      question: '3. Preciso imprimir todas as +147 atividades de uma vez?',
      answer: 'Não. Você pode escolher apenas as páginas que deseja utilizar naquele momento e imprimir conforme a necessidade da criança.',
    },
    {
      question: '4. Vou receber algum material físico em casa?',
      answer: 'Não. O produto é 100% digital. Após a confirmação da compra, você recebe acesso aos arquivos e pode imprimir as páginas que quiser.',
    },
    {
      question: '5. E se meu filho não se interessar pelo material?',
      answer: 'Você conta com 7 dias de garantia para conhecer o produto. Se entender que ele não atende às suas expectativas, poderá solicitar o reembolso dentro do período estabelecido.',
    },
  ],
  footer: {
    brand: 'Atividades Escolares Minecraft',
    copyright: '© 2026 Todos os direitos reservados.',
  },
};
